### ISSUE TITLE
ACP rule disable

### ISSUE THREAD

**Issue by karmicgeezer** [daxm/fmcapi#35]
A question if I may, is there any reason why the following to disable an existing ACP rule isn't working, please note I'm only put the relevant few lines below for brevity.

Disabling a rule fails:

acp = AccessControlPolicy(fmc=fmc1, name=policy)
acprule = ACPRule(fmc=fmc1, acp_name=acp.name)
acprule.enabled = False
response = acprule.put()

response returns None

Deleting a rule works just fine:

acp = AccessControlPolicy(fmc=fmc1, name=policy)
acprule = ACPRule(fmc=fmc1, acp_name=acp.name)
response = acprule.delete()

Many thanks in advance,

Andy

**Comment by marksull** [comment]
Hey @karmicgeezer 

A couple things:

First, to be able to modify a Rule you need to load it so that fmcapi has the ID of the rule. For example:

```
acp = AccessControlPolicy(fmc=fmc1, name=policy)
acprule = ACPRule(fmc=fmc1, acp_name=acp.name)
acprule.name = "The name of your rule"
response = acprule.get()
print(response['name'])
print(response['id'])
print(response['enabled'])
```

Now that you have the actual rule, I would expect, exactly as you did, that by setting the enabled flag and performing a put that the value would be updated. Unfortunately the way the package is working right now is that if you don't explicitly pass in the value you want to change to the put call (and this applies to bool values only), then its not honouring the new value. So to get around this do the following:

```
acp = AccessControlPolicy(fmc=fmc1, name=policy)
acprule = ACPRule(fmc=fmc1, acp_name=acp.name)
acprule.name = "The name of your rule"
response = acprule.get()
print(response['name'])
print(response['id'])
print(response['enabled'])
response = acprule.put(enabled=False)
print(response['name'])
print(response['id'])
print(response['enabled'])
```

I consider this to be a bug because its non-intuitive and only applies to bools. I'll have a chat with the package owner/creator @daxm and see how we can solve this.

With respect to your delete example above it won't work because the acprule has no id. Again you will need to perform a get (to load the ID based on the name of the rule) before you can delete it. For example:

```
acp = AccessControlPolicy(fmc=fmc1, name=policy)
acprule = ACPRule(fmc=fmc1, acp_name=acp.name)
acprule.name = "The name of your rule"
response = acprule.get()
print(response['name'])
print(response['id'])
response = acprule.delete()
print(response)
```

**Comment by karmicgeezer** [comment]
Mark,

Ah yes, I was aware of this but forgot.

Thank you very much for such a quick and comprehensive response, much appreciated!

As an aside, when performing a large number of get methods, I had a quick look at using the requests-cache module which seems to have significantly sped up the process.

Thank you all again for the work on what has become the defacto library to use for all FMC work!!

All the best,

Andy

**Comment by karmicgeezer** [comment]
Sorry... forgot to close this, all working a treat.
